return {
  'nvim-treesitter/nvim-treesitter',
  branch = 'main',
  lazy = false,
  build = ':TSUpdate',
  priority = 100,
  opts = {
    ensure_installed = {
      'lua',
      'vim',
      'vimdoc',
      'javascript',
      'typescript',
      'python',
      'rust',
      'go',
      'html',
      'css',
      'json',
      'yaml',
      'toml',
      'markdown',
      'bash',
      'csharp',
      'razor',
    },
    auto_install = true,
    highlight = {
      enable = true,
    },
    indent = { enable = true },
    incremental_selection = {
      enable = true,
      keymaps = {
        init_selection = '<CR>',
        node_incremental = '<CR>',
        node_decremental = '<BS>',
      },
    },
  },
}
